# `title` will be used as a heading and as the title of the html file.
title = "A schedule title"

# `notes` is an unordered list of items in the right column.
notes = [
    "Item 1",
    "Item 2"
]

# The date range for the schedule
start_date = "2017-6-25"
end_date = "2017-9-01"

# `shifts` are the regular times that the sound system will be used.  Check the
# spelling of these because this list will be used to verify that the shifts in
# the operator table are spelled correctly.  It will also be used for display in
# the final html file.
[shifts]
Sunday = ["Sun AM", "Sun PM"]
Wednesday = ["Wed"]

# `operators` table defines the availability of each operator.  Use the spelling
# from `shifts` above for specifying `operators.shifts` below.  The array order
# is maintained.
[[operators]]
name = "Bill"
shifts = []
phone = "123-456-7890"

[[operators]]
name = "Bob"
shifts = ["Sun AM", "Wed"]
phone = "222-222-2222"

[[operators]]
name = "Billybob"
shifts = ["Sun AM", "Sun PM", "Wed"]
phone = "333-333-3333"

[[operators]]
name = "Bobby-robert"
shifts = ["Sun PM", "Wed"]
phone = "444-444-4444"
